export const CREATE_CONTRACT_SUCCESS ='CREATE_CONTRACT_SUCCESS';
export const UPDATE_CONTRACT_SUCCESS = "UPDATE_CONTRACT_SUCCESS"; 
export const LOAD_CONTRACTS_SUCCESS = "LOAD_CONTRACTS_SUCCESS";

export const CREATE_CATEGORY_SUCCESS ='CREATE_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS"; 
export const LOAD_CATEGORY_SUCCESS = "LOAD_CATEGORY_SUCCESS";
